### ISSUE TITLE
ng build --prod error when using version 2.0.0

### ISSUE THREAD

**Issue by dkregen** [AckerApple/angular-file#70]
This is what I got when building the project:
```
ERROR in ./node_modules/angular-file/fesm5/angular-file.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/home/wallet/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/home/wallet/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/home/wallet/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/home/wallet/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/home/wallet/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/wallet/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/home/wallet/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/home/wallet/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/wallet/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/home/wallet/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/home/wallet/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/wallet/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/home/wallet/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/home/wallet/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/wallet/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/home/wallet/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16599:21)
```
This is the package.json:
```
{
  "name": "wallet",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "node index.js",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.0.3",
    "@angular/common": "~8.0.3",
    "@angular/compiler": "~8.0.3",
    "@angular/core": "~8.0.3",
    "@angular/forms": "~8.0.3",
    "@angular/platform-browser": "~8.0.3",
    "@angular/platform-browser-dynamic": "~8.0.3",
    "@angular/router": "~8.0.3",
    "angular-particle": "^1.0.4",
    "bootstrap": "^4.3.1",
    "bs-stepper": "^1.7.0",
    "chart.js": "^2.8.0",
    "css-ripple-effect": "^1.0.5",
    "express": "^4.17.1",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "ngx-qrcode2": "^0.0.9",
    "ngx-webcam": "^0.2.6",
    "popper.js": "^1.15.0",
    "rxjs": "~6.4.0",
    "shards-ui": "^3.0.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.6",
    "@angular/cli": "~8.0.6",
    "@angular/compiler-cli": "~8.0.3",
    "@angular/language-service": "~8.0.3",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "angular-file": "^2.0.0",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}
```

These are the steps that I exactly do:
1. `npm install angular-file --save-dev`
2. `npm install`
3. `npm run build`

**Comment by AckerApple** [comment]
Never seen that one before. At this time I can only think to have you try upgrading to Angular 8.2

Wondering if we search the error if we might find any help. I don’t have time at this time to help at this time

**Comment by dkregen** [comment]
Hello, thanks for your reply. I already did trial and error for this problem. The best solution for now is using the version 1.3.2 of angular-file.
`"angular-file": "1.3.2"`

**Comment by jps1st** [comment]
Hi. Any updates on fixes aside from downgrading to 1.3.2? I'm having the same problem.

**Comment by AckerApple** [comment]
The demo for this package builds just fine.

Demo branch:
https://github.com/AckerApple/angular-file/tree/gh-pages

Make sure you have latest Angular.

Here is the package.json from the demo:
https://github.com/AckerApple/angular-file/blob/gh-pages/package.json

**Comment by M-Blobby** [comment]
Same problem when I run :
ng build --prod=true
With the flag prod=false, it works fine.
I'm with angular 8.2

**Comment by stanikzai** [comment]
The same problem when I run ng build --prod --aot
angular version is 8.0.6

**Comment by AckerApple** [comment]
Someone knows what to do, point it out. Make pull request. Angular bits me in the ass yearly with bundling changes. Not gonna hunt down the fix until I need it in my business.

Let’s be a community, help wanted

**Comment by AckerApple** [comment]
This package has now been built using new Angular 9

Please acquire version 3.0.0 of this package and try it out.
